project:
  type: website
  output-dir: docs
  
website:
  title: "cansavvy::Candy_Bytes()"
  navbar:
    right:
      - text: cansavvy.com
        href: https://www.cansavvy.com/
      - icon: github
        href: https://github.com/cansavvy
format:
  html:
    theme: morph
    css: styles.css

editor: visual
