project:
  type: website
  output-dir: docs

website:
  title: "cansavvy::Candy_Bytes()"
  navbar:
    right:
      - text: cansavvy.com
        href: https://www.cansavvy.com/
      - icon: github
        href: https://github.com/cansavvy
      - text: Subscribe!
        href: https://forms.gle/muRJQALEacH8mJaS7
format:
  html:
    theme: morph
    css: styles.css

editor: visual
